<?php
/** Run only against the disposable fixture; native harness may override FG_TEST_WP_ROOT. */
$root=defined('FG_TEST_WP_ROOT') ? FG_TEST_WP_ROOT : '/wordpress';
require_once $root.'/wp-load.php';
foreach(['core','auth','oauth'] as $module) require_once $root.'/wp-content/plugins/jalin-mcp-gateway/includes/class-'.$module.'.php';
$_SERVER['HTTPS']='on'; $_SERVER['SERVER_PORT']='443'; $_SERVER['REMOTE_ADDR']='192.0.2.44';
update_option('home','https://gateway.example.test'); update_option('siteurl','https://gateway.example.test');
global $wp_rewrite,$wpdb; $wp_rewrite->set_permalink_structure('/%postname%/');
$admin=get_users(['role'=>'administrator','number'=>1])[0]; wp_set_current_user($admin->ID);
$settings=['enabled'=>true,'oauth_enabled'=>true,'writes'=>true,'sensitive'=>true,'write_mode'=>'reviewed','users'=>[$admin->ID],'origins'=>[],'finance_mappings'=>['fixture'=>['fee_key'=>'_fee','fee_divisor'=>100]]];
update_option('fg_settings',$settings); add_option('fg_oauth_epoch',wp_generate_uuid4(),'',false); $epoch=get_option('fg_oauth_epoch'); $results=[];
function oa_assert($condition,$message): void { if(!$condition) throw new RuntimeException($message); }
function oa_case($name,$callback): void { global $results; try{$callback();$results[]=['name'=>$name,'pass'=>true];}catch(Throwable $e){$results[]=['name'=>$name,'pass'=>false,'error'=>$e->getMessage()];} }
function oa_t($name): string {return FG_Core::table($name);}
function oa_req($path,$params=[]): WP_REST_Request {$r=new WP_REST_Request('POST','/jalin-mcp/v1/'.$path); if($path==='oauth/register'){$r->set_header('Content-Type','application/json');$r->set_body(wp_json_encode($params));}else{$r->set_header('Content-Type','application/x-www-form-urlencoded');$r->set_body_params($params);$r->set_body(http_build_query($params));}return $r;}
function oa_client($name): array {$r=FG_OAuth::register_client(oa_req('oauth/register',['client_name'=>$name,'redirect_uris'=>['https://claude.ai/api/mcp/auth_callback'],'token_endpoint_auth_method'=>'none']));oa_assert($r->get_status()===201,'Registration failed');return $r->get_data();}
function oa_grant($client,$override=[]): array {global $wpdb,$admin;$row=array_replace(['id'=>wp_generate_uuid4(),'client_id'=>$client['client_id'],'user_id'=>$admin->ID,'user_hash'=>hash_hmac('sha256',$admin->ID.'|'.$admin->user_pass.'|'.get_option('fg_oauth_epoch'),wp_salt('auth')),'resource'=>FG_OAuth::resource(),'allow_writes'=>1,'allow_sensitive'=>1,'status'=>'active','created'=>time(),'expires'=>time()+DAY_IN_SECONDS,'last_used'=>0],$override);oa_assert($wpdb->insert(oa_t('oauth_grants'),$row)===1,'Grant insert failed');return $row;}
function oa_list($id): array {$rows=FG_OAuth::connections();oa_assert(!is_wp_error($rows),'List failed');foreach($rows as $row)if($row['id']===$id)return $row;throw new RuntimeException('Connection missing');}
function oa_token($g): string {global $wpdb;$raw=rtrim(strtr(base64_encode(random_bytes(32)),'+/','-_'),'=');oa_assert($wpdb->insert(oa_t('oauth_tokens'),['hash'=>hash('sha256',$raw),'grant_id'=>$g['id'],'kind'=>'access','status'=>'active','created'=>time(),'expires'=>time()+3600])===1,'Token insert failed');return $raw;}
function oa_permission($token){$r=new WP_REST_Request('POST','/jalin-mcp/v1/mcp');$r->set_header('Authorization','Bearer '.$token);oa_assert(FG_Auth::permission($r)===true,'Bearer rejected');return $r;}
$changes=oa_t('changes');$audit=oa_t('audit');
$wpdb->query("DROP TABLE IF EXISTS $changes");$wpdb->query("DROP TABLE IF EXISTS $audit");
$wpdb->query("CREATE TABLE $changes (id char(36) NOT NULL,user_id bigint unsigned NOT NULL,credential_id char(36) NOT NULL,tool varchar(64) NOT NULL,arguments longtext NOT NULL,digest char(64) NOT NULL,status varchar(16) NOT NULL,created bigint unsigned NOT NULL,expires bigint unsigned NOT NULL,reviewer_id bigint unsigned NOT NULL DEFAULT 0,PRIMARY KEY (id),KEY status_created(status,created),KEY user_created(user_id,created))");
$wpdb->query("CREATE TABLE $audit (id bigint unsigned NOT NULL AUTO_INCREMENT,user_id bigint unsigned NOT NULL,tool varchar(64) NOT NULL,outcome varchar(40) NOT NULL,change_id varchar(36) NOT NULL DEFAULT '',created bigint unsigned NOT NULL,PRIMARY KEY (id),KEY created(created))");
$old=wp_generate_uuid4();$wpdb->insert($changes,['id'=>$old,'user_id'=>$admin->ID,'credential_id'=>wp_generate_uuid4(),'tool'=>'fixture','arguments'=>'{}','digest'=>hash('sha256','{}'),'status'=>'pending','created'=>time(),'expires'=>time()+900]);
$wpdb->insert($audit,['user_id'=>$admin->ID,'tool'=>'old_read','outcome'=>'success','created'=>time()]);
update_option('fg_db_version','0.2.0');FG_Core::maybe_upgrade();FG_Auth::boot();
oa_case('real legacy schema gains verified columns and ordered indexes',function(){oa_assert(get_option('fg_db_version')==='0.3.0'&&get_option('fg_oauth_schema')==='3','Migration markers missing');oa_assert(FG_Core::schema_ready(oa_t('audit'),['auth_source','oauth_client_id','oauth_grant_id','client_name'],['client_created'=>['oauth_client_id','created']]),'Audit schema incomplete');});
oa_case('historical audit neutral; legacy unfinished approval revoked',function()use($wpdb,$old,$changes,$audit){$r=$wpdb->get_row("SELECT * FROM $audit WHERE tool='old_read'",ARRAY_A);oa_assert($r['auth_source']===''&&$r['oauth_client_id']===''&&$r['client_name']==='','Invented identity');oa_assert($wpdb->get_var($wpdb->prepare("SELECT status FROM $changes WHERE id=%s",$old))==='revoked','Old approval executable');});
oa_case('migration preserves settings and OAuth epoch',function()use($settings,$epoch){oa_assert(FG_Core::settings()===$settings&&get_option('fg_oauth_epoch')===$epoch,'Settings or epoch changed');});
oa_case('zero grants means genuine empty list',function(){oa_assert(FG_OAuth::connections()===[],'Expected empty list');});
$claude=oa_client('Claude');$gptclient=oa_client('ChatGPT');$legacy=oa_grant($claude);$gpt=oa_grant($gptclient,['consent_recorded_at'=>time()]);
oa_case('real listing separates clients for same user and preserves approved access keys',function()use($legacy,$gpt){$a=oa_list($legacy['id']);$b=oa_list($gpt['id']);oa_assert($a['client_name']==='Claude'&&$b['client_name']==='ChatGPT'&&$a['user_id']===$b['user_id']&&$a['writes']&&$a['sensitive'],'Wrong rows');oa_assert(!isset($a['user_hash'])&&!isset($a['resource']),'Internal fields exposed');});
oa_case('legacy unknown history remains unknown',function()use($legacy){$r=oa_list($legacy['id']);oa_assert($r['lifecycle_status']==='authorization_recorded'&&$r['tokens_issued_at']===null&&$r['first_authenticated_at']===null,'Invented history');});
oa_case('consent-only record shows finish connecting',function()use($gpt){oa_assert(oa_list($gpt['id'])['lifecycle_status']==='approval_received','Consent state wrong');});
$token=oa_token($legacy);
oa_case('retained token proves issuance without fabricated timestamp',function()use($legacy){$r=oa_list($legacy['id']);oa_assert($r['lifecycle_status']==='authorized'&&$r['tokens_issued_at']===null,'Bad backfill');});
oa_case('repeat migration preserves token hash grant and issuer',function()use($wpdb,$token,$epoch){$query=$wpdb->prepare('SELECT * FROM '.oa_t('oauth_tokens').' WHERE hash=%s',hash('sha256',$token));$before=$wpdb->get_row($query,ARRAY_A);$issuer=FG_OAuth::issuer();update_option('fg_db_version','0.2.0');update_option('fg_oauth_schema','1');FG_Core::maybe_upgrade();FG_Core::activate();oa_assert($before===$wpdb->get_row($query,ARRAY_A)&&FG_OAuth::issuer()===$issuer&&get_option('fg_oauth_epoch')===$epoch,'Credentials altered');oa_assert(!is_wp_error(FG_OAuth::authenticate($token)),'Old token rejected');});
oa_case('authentication supplies verified client and lifecycle evidence',function()use($token,$legacy){$i=FG_OAuth::authenticate($token);$r=oa_list($legacy['id']);oa_assert($i['auth_source']==='oauth'&&$i['oauth_client_id']===$legacy['client_id']&&$i['oauth_grant_id']===$legacy['id']&&$i['client_name']==='Claude','Identity wrong');oa_assert($r['lifecycle_status']==='active'&&$r['first_authenticated_at']===null&&$r['last_used']>0,'Lifecycle missing');});
oa_case('listing does not mutate timestamps',function()use($wpdb,$legacy){$q=$wpdb->prepare('SELECT last_used,first_authenticated_at,tokens_issued_at FROM '.oa_t('oauth_grants').' WHERE id=%s',$legacy['id']);$before=$wpdb->get_row($q,ARRAY_A);FG_OAuth::connections();oa_assert($before===$wpdb->get_row($q,ARRAY_A),'Listing wrote evidence');});
$revoked=oa_grant($claude,['status'=>'revoked']);$expired=oa_grant($claude,['expires'=>time()-1]);$missing=oa_grant(['client_id'=>wp_generate_uuid4()]);
oa_case('revoked expired and missing-client records are truthful',function()use($revoked,$expired,$missing){oa_assert(oa_list($revoked['id'])['lifecycle_status']==='revoked'&&oa_list($expired['id'])['lifecycle_status']==='expired'&&oa_list($missing['id'])['lifecycle_status']==='reconnect_required','Invalid status projection');});
oa_case('effective policy intersects original consent',function()use($settings,$legacy){update_option('fg_settings',array_replace($settings,['writes'=>false,'sensitive'=>false]));$r=oa_list($legacy['id']);update_option('fg_settings',$settings);oa_assert($r['writes']&&$r['sensitive']&&!$r['effective_writes']&&!$r['effective_sensitive'],'Policy projection wrong');});
oa_case('disabled gateway projects reconnect required',function()use($settings,$legacy){update_option('fg_settings',array_replace($settings,['enabled'=>false]));$r=oa_list($legacy['id']);update_option('fg_settings',$settings);oa_assert($r['lifecycle_status']==='reconnect_required','Disabled appears active');});
oa_case('database error returns sanitized WP_Error',function(){$fault=static fn($sql)=>str_contains($sql,'SELECT g.*,c.id AS registered_client_id')?'SELECT * FROM fg_deliberately_missing_connection_table':$sql;add_filter('query',$fault);try{$r=FG_OAuth::connections();}finally{remove_filter('query',$fault);}oa_assert(is_wp_error($r)&&$r->get_error_code()==='fg_oauth_connections_storage'&&!str_contains($r->get_error_message(),'SELECT')&&!str_contains($r->get_error_message(),'fg_deliberately'),'Failure hidden or leaked');});
oa_case('read propose apply failure audit preserve client while admin review is explicit',function()use($token,$legacy,$wpdb){$r=oa_permission($token);foreach(['read','propose','apply','failure'] as $outcome)oa_assert(FG_Core::audit('client_fixture',$outcome),'Audit failed');FG_Core::audit('admin_fixture','approve','',['auth_source'=>'wordpress_admin']);$rows=$wpdb->get_results('SELECT * FROM '.oa_t('audit')." WHERE tool='client_fixture'",ARRAY_A);oa_assert(count($rows)===4,'Outcomes missing');foreach($rows as $row)oa_assert($row['client_name']==='Claude'&&$row['oauth_client_id']===$legacy['client_id'],'Wrong snapshot');$ar=$wpdb->get_row('SELECT * FROM '.oa_t('audit')." WHERE tool='admin_fixture'",ARRAY_A);oa_assert($ar['auth_source']==='wordpress_admin'&&$ar['oauth_client_id']===''&&$ar['client_name']==='WordPress Admin','Admin attributed to client');apply_filters('rest_request_after_callbacks',new WP_REST_Response([]),[],$r);oa_assert(FG_Auth::audit_context()['auth_source']==='','Context survived request');});
oa_case('WordPress Allow-header probes reuse completed decisions without identity or extra rate hits',function()use($token,$admin,$wpdb){foreach(['oauth','application_password'] as $source){if($source==='oauth'){$r=oa_permission($token);}else{wp_set_current_user($admin->ID);do_action('application_password_did_authenticate',$admin,['uuid'=>wp_generate_uuid4()]);$r=new WP_REST_Request('POST','/jalin-mcp/v1/mcp');oa_assert(FG_Auth::permission($r)===true,'Fresh password failed');}$bucket=$admin->ID.':'.intdiv(time(),60);$q=$wpdb->prepare('SELECT hits FROM '.oa_t('limits').' WHERE bucket=%s',$bucket);$hits=$wpdb->get_var($q);apply_filters('rest_request_after_callbacks',new WP_REST_Response([]),[],$r);$probe=static function($response,$server,$request){for($i=0;$i<3;$i++)oa_assert(FG_Auth::permission($request)===true,'Completed header decision lost');return $response;};add_filter('rest_post_dispatch',$probe,1,3);try{apply_filters('rest_post_dispatch',new WP_REST_Response([]),rest_get_server(),$r);}finally{remove_filter('rest_post_dispatch',$probe,1);}oa_assert($hits===$wpdb->get_var($q)&&FG_Auth::audit_context()['auth_source']==='','Header probe reauthenticated or charged rate');}});
oa_case('wrong route clears prior OAuth identity',function()use($token){oa_permission($token);oa_assert(is_wp_error(FG_Auth::permission(new WP_REST_Request('GET','/wp/v2/users')))&&FG_Auth::audit_context()['auth_source']==='','Identity survived wrong route');});
oa_case('Application Password context is fresh and cannot be reused by cookie-only request',function()use($admin,$wpdb){wp_set_current_user($admin->ID);do_action('application_password_did_authenticate',$admin,['uuid'=>wp_generate_uuid4()]);$r=new WP_REST_Request('POST','/jalin-mcp/v1/mcp');oa_assert(FG_Auth::permission($r)===true,'App password rejected');FG_Core::audit('app_fixture','read');$row=$wpdb->get_row('SELECT * FROM '.oa_t('audit')." WHERE tool='app_fixture'",ARRAY_A);oa_assert($row['auth_source']==='application_password'&&$row['oauth_client_id']==='','Wrong App identity');oa_assert(is_wp_error(FG_Auth::permission($r))&&FG_Auth::audit_context()['auth_source']==='','Cookie reused identity');});
oa_case('nested REST completion retains outer OAuth identity',function()use($token){oa_permission($token);apply_filters('rest_request_after_callbacks',new WP_REST_Response([]),[],new WP_REST_Request('GET','/wp/v2/pages'));oa_assert(FG_Auth::audit_context()['client_name']==='Claude','Nested callback lost identity');FG_Auth::reset_context();});
oa_case('sanitized bounded client snapshots survive grant/client deletion',function()use($wpdb){$c=oa_client('Fixture <b>Y</b>');$g=oa_grant($c);oa_permission(oa_token($g));FG_Core::audit('snapshot_fixture','read');FG_Auth::reset_context();$wpdb->delete(oa_t('oauth_grants'),['id'=>$g['id']]);$wpdb->delete(oa_t('oauth_clients'),['id'=>$c['client_id']]);$r=$wpdb->get_row('SELECT * FROM '.oa_t('audit')." WHERE tool='snapshot_fixture'",ARRAY_A);oa_assert(strlen($r['client_name'])<=120&&!str_contains($r['client_name'],'<')&&$r['oauth_grant_id']===$g['id'],'Snapshot unsafe/lost');});
wp_set_current_user($admin->ID);$expiry=time()+3600;$session=WP_Session_Tokens::get_instance($admin->ID)->create($expiry);$_COOKIE[LOGGED_IN_COOKIE]=wp_generate_auth_cookie($admin->ID,$expiry,'logged_in',$session);
$realclient=oa_client('Real Consent Fixture');$verifier=str_repeat('p',43);$challenge=rtrim(strtr(base64_encode(hash('sha256',$verifier,true)),'+/','-_'),'=');
oa_case('real consent issuance and refresh preserve authorization lifecycle',function()use($realclient,$challenge,$verifier,$wpdb){$p=['response_type'=>'code','client_id'=>$realclient['client_id'],'redirect_uri'=>$realclient['redirect_uris'][0],'resource'=>FG_OAuth::resource(),'scope'=>'mcp','state'=>'fixture','code_challenge'=>$challenge,'code_challenge_method'=>'S256'];$pending=FG_OAuth::begin_consent($p);oa_assert(!is_wp_error($pending),'Consent start failed');$allowed=FG_OAuth::complete_consent($pending['id'],true);oa_assert(!is_wp_error($allowed),'Consent failed');parse_str(wp_parse_url($allowed,PHP_URL_QUERY),$redirect);$g=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.oa_t('oauth_grants').' WHERE client_id=%s',$realclient['client_id']),ARRAY_A);oa_assert(oa_list($g['id'])['lifecycle_status']==='approval_received','Consent evidence missing');$r=FG_OAuth::token(oa_req('oauth/token',['grant_type'=>'authorization_code','code'=>$redirect['code'],'code_verifier'=>$verifier,'client_id'=>$realclient['client_id'],'redirect_uri'=>$realclient['redirect_uris'][0],'resource'=>FG_OAuth::resource()]));oa_assert($r->get_status()===200,'Token failed');$before=oa_list($g['id']);oa_assert($before['lifecycle_status']==='authorized'&&$before['tokens_issued_at']>0,'Token evidence missing');$refresh=FG_OAuth::token(oa_req('oauth/token',['grant_type'=>'refresh_token','refresh_token'=>$r->get_data()['refresh_token'],'client_id'=>$realclient['client_id'],'resource'=>FG_OAuth::resource()]));oa_assert($refresh->get_status()===200,'Refresh failed');$after=oa_list($g['id']);oa_assert($before['id']===$after['id']&&$before['created']===$after['created']&&$before['tokens_issued_at']===$after['tokens_issued_at'],'Refresh replaced history');$identity=FG_OAuth::authenticate($refresh->get_data()['access_token']);$used=oa_list($g['id']);oa_assert(!is_wp_error($identity)&&$used['first_authenticated_at']>0&&$used['lifecycle_status']==='active','New grant first-authentication evidence missing');});
final class OA_DB_Proxy {private $db;private $fault;public function __construct($db,$fault){$this->db=$db;$this->fault=$fault;}public function __get($k){return $this->db->$k;}public function __set($k,$v){$this->db->$k=$v;}public function __call($m,$a){$r=$this->db->$m(...$a);return ($this->fault)($m,$a,$r);}}
oa_case('missing audit column prevents migration marker and retry succeeds',function()use(&$wpdb){$real=$wpdb;update_option('fg_db_version','0.2.0');$wpdb=new OA_DB_Proxy($real,static function($m,$a,$r){return $m==='get_results'&&str_starts_with($a[0]??'','SHOW COLUMNS FROM `'.oa_t('audit').'`')?array_values(array_filter($r,static fn($x)=>$x['Field']!=='client_name')):$r;});try{FG_Core::activate();oa_assert(get_option('fg_db_version')==='0.2.0','Marker advanced without column');}finally{$wpdb=$real;}FG_Core::maybe_upgrade();oa_assert(get_option('fg_db_version')==='0.3.0','Retry failed');});
oa_case('missing OAuth index prevents marker and retry preserves epoch',function()use(&$wpdb,$epoch){$real=$wpdb;update_option('fg_oauth_schema','1');$wpdb=new OA_DB_Proxy($real,static function($m,$a,$r){return $m==='get_results'&&str_starts_with($a[0]??'','SHOW INDEX FROM `'.oa_t('oauth_grants').'`')?array_values(array_filter($r,static fn($x)=>$x['Key_name']!=='client_id')):$r;});try{FG_OAuth::install();oa_assert(get_option('fg_oauth_schema')==='1','Marker advanced without index');}finally{$wpdb=$real;}FG_OAuth::maybe_upgrade();oa_assert(get_option('fg_oauth_schema')==='3'&&get_option('fg_oauth_epoch')===$epoch,'Retry failed/epoch rotated');});
oa_case('failed revocation on deactivation cannot revive an old token after re-enable',function()use($token,$admin,$wpdb){oa_assert(!is_wp_error(FG_OAuth::authenticate($token)),'Token invalid before deactivation');$fault=static fn($sql)=>str_starts_with($sql,'UPDATE')&&(str_contains($sql,'fg_oauth_epoch')||str_contains($sql,oa_t('oauth_grants')))?'SELECT * FROM oa_expected_missing_revoke_table':$sql;$prior=$wpdb->suppress_errors(true);add_filter('query',$fault);try{FG_Core::deactivate();$disabled=FG_Core::settings();oa_assert(empty($disabled['enabled'])&&!empty($disabled['_oauth_revoke_pending']),'Disable did not persist pending marker');$failed=FG_Settings::enable_for_user($admin->ID,FG_Settings::fingerprint('connection'));oa_assert(is_wp_error($failed)&&empty(FG_Core::settings()['enabled']),'Failed revoke allowed re-enable');}finally{remove_filter('query',$fault);$wpdb->suppress_errors($prior);}FG_Core::activate();$enabled=FG_Settings::enable_for_user($admin->ID,FG_Settings::fingerprint('connection'));oa_assert(!is_wp_error($enabled)&&is_wp_error(FG_OAuth::authenticate($token)),'Old credential revived after re-enable');});
oa_case('deactivation aborts if disabled state cannot be persisted',function()use($wpdb){$fault=static fn($sql)=>str_starts_with($sql,'UPDATE')&&str_contains($sql,'option_value=')&&str_contains($sql,'fg_settings')?'SELECT * FROM oa_expected_missing_settings_table':$sql;$die=static fn()=>static function($message){throw new RuntimeException((string)$message);};$prior=$wpdb->suppress_errors(true);add_filter('query',$fault);add_filter('wp_die_handler',$die);$aborted=false;try{FG_Core::deactivate();}catch(RuntimeException $error){$aborted=str_contains($error->getMessage(),'MCP access could not be disabled');}finally{remove_filter('query',$fault);remove_filter('wp_die_handler',$die);$wpdb->suppress_errors($prior);}oa_assert($aborted&&!empty(FG_Core::settings()['enabled']),'Deactivation falsely completed without persisting disable');});
FG_Auth::reset_context();echo json_encode(['passed'=>count(array_filter($results,static fn($r)=>$r['pass'])),'total'=>count($results),'database_class'=>get_class($wpdb),'cases'=>$results],JSON_PRETTY_PRINT);
