<?php
/** Disposable local WP fixture: native MySQL execution remains a separate gate. */
$root=defined('FG_TEST_WP_ROOT') ? FG_TEST_WP_ROOT : '/wordpress';
require_once $root.'/wp-load.php';
foreach(['core','settings','auth','oauth','tools'] as $module) require_once $root.'/wp-content/plugins/fames-mcp-gateway/includes/class-'.$module.'.php';
$_SERVER['HTTPS']='on'; $_SERVER['SERVER_PORT']='443'; $_SERVER['REMOTE_ADDR']='192.0.2.51';
update_option('home','https://gateway.example.test'); update_option('siteurl','https://gateway.example.test');
global $wp_rewrite,$wpdb; $wp_rewrite->set_permalink_structure('/%postname%/');
$admin=get_users(['role'=>'administrator','number'=>1])[0]; wp_set_current_user($admin->ID);
$base=['enabled'=>true,'oauth_enabled'=>true,'writes'=>true,'sensitive'=>false,'users'=>[$admin->ID],'origins'=>[],'finance_mappings'=>[]];
update_option('fg_settings',$base); FG_Core::activate(); FG_Auth::boot(); $results=[];
function yo_assert($condition,$message): void {if(!$condition)throw new RuntimeException($message);}
function yo_case($name,$callback): void {global $results;try{$callback();$results[]=['name'=>$name,'pass'=>true];}catch(Throwable $e){$results[]=['name'=>$name,'pass'=>false,'error'=>$e->getMessage()];}}
function yo_t($name): string {return FG_Core::table('oauth_'.$name);}
function yo_settings($values): void {global $base;update_option('fg_settings',array_replace($base,$values));}
function yo_req($path,$data=[]): WP_REST_Request {$r=new WP_REST_Request('POST','/fames-mcp/v1/oauth/'.$path);if($path==='register'){$r->set_header('Content-Type','application/json');$r->set_body(wp_json_encode($data));}else{$r->set_header('Content-Type','application/x-www-form-urlencoded');$r->set_body_params($data);$r->set_body(http_build_query($data));}return $r;}
function yo_login($user=null): void {global $admin;$user??=$admin;FG_Auth::reset_context();wp_set_current_user($user->ID);$expiry=time()+3600;$session=WP_Session_Tokens::get_instance($user->ID)->create($expiry);$_COOKIE[LOGGED_IN_COOKIE]=wp_generate_auth_cookie($user->ID,$expiry,'logged_in',$session);}
function yo_client($name='YOLO Fixture'): array {$r=FG_OAuth::register_client(yo_req('register',['client_name'=>$name,'redirect_uris'=>['https://claude.ai/api/mcp/auth_callback'],'token_endpoint_auth_method'=>'none']));yo_assert($r->get_status()===201,'Registration failed: '.wp_json_encode($r->get_data()));return $r->get_data();}
function yo_begin($c,$extra=[]): array {$v=str_repeat('a',43);$challenge=rtrim(strtr(base64_encode(hash('sha256',$v,true)),'+/','-_'),'=');$r=FG_OAuth::begin_consent(array_replace(['response_type'=>'code','client_id'=>$c['client_id'],'redirect_uri'=>$c['redirect_uris'][0],'resource'=>FG_OAuth::resource(),'scope'=>'mcp','state'=>'fixture','code_challenge'=>$challenge,'code_challenge_method'=>'S256'],$extra));yo_assert(!is_wp_error($r),'Consent begin failed: '.(is_wp_error($r)?$r->get_error_message():''));return $r;}
function yo_complete($pending,$c): array {global $wpdb;$url=FG_OAuth::complete_consent($pending['id'],true);yo_assert(!is_wp_error($url),'Consent failed');parse_str(wp_parse_url($url,PHP_URL_QUERY),$query);$r=FG_OAuth::token(yo_req('token',['grant_type'=>'authorization_code','client_id'=>$c['client_id'],'redirect_uri'=>$c['redirect_uris'][0],'resource'=>FG_OAuth::resource(),'code'=>$query['code'],'code_verifier'=>str_repeat('a',43)]));yo_assert($r->get_status()===200,'Token exchange failed: '.wp_json_encode($r->get_data()));$data=$r->get_data();$row=$wpdb->get_row($wpdb->prepare('SELECT g.* FROM '.yo_t('grants').' g JOIN '.yo_t('tokens').' t ON t.grant_id=g.id WHERE t.hash=%s',hash('sha256',$data['access_token'])),ARRAY_A);return ['grant'=>$row,'token'=>$data,'client'=>$c];}
function yo_connect(): array {yo_login();$c=yo_client();return yo_complete(yo_begin($c),$c);}
function yo_auth($token): WP_REST_Request {$r=new WP_REST_Request('POST','/fames-mcp/v1/mcp');$r->set_header('Authorization','Bearer '.$token);$p=FG_Auth::permission($r);yo_assert($p===true,'Permission rejected: '.(is_wp_error($p)?$p->get_error_message():''));return $r;}
function yo_list($id): array {$rows=FG_OAuth::connections();yo_assert(!is_wp_error($rows),'Connection listing failed');foreach($rows as $r)if($r['id']===$id)return $r;throw new RuntimeException('Connection missing');}
function yo_refresh($connection): array {$r=FG_OAuth::token(yo_req('token',['grant_type'=>'refresh_token','client_id'=>$connection['client']['client_id'],'resource'=>FG_OAuth::resource(),'refresh_token'=>$connection['token']['refresh_token']]));yo_assert($r->get_status()===200,'Refresh failed');return $r->get_data();}
yo_case('missing mode defaults to reviewed without altering stored settings',function()use($base){yo_assert(FG_Core::settings()['write_mode']==='reviewed'&&FG_Core::fresh_settings()['write_mode']==='reviewed','Wrong default');yo_assert(get_option('fg_settings')===$base,'Read altered saved settings');});
$gtable=yo_t('grants');$wpdb->query("DROP TABLE $gtable");
$wpdb->query("CREATE TABLE $gtable (id char(36) NOT NULL,client_id char(36) NOT NULL,user_id bigint unsigned NOT NULL,user_hash char(64) NOT NULL,resource text NOT NULL,allow_writes tinyint NOT NULL DEFAULT 0,allow_sensitive tinyint NOT NULL DEFAULT 0,status varchar(16) NOT NULL,created bigint unsigned NOT NULL,expires bigint unsigned NOT NULL,last_used bigint unsigned NOT NULL DEFAULT 0,consent_recorded_at bigint unsigned DEFAULT NULL,tokens_issued_at bigint unsigned DEFAULT NULL,first_authenticated_at bigint unsigned DEFAULT NULL,PRIMARY KEY (id),KEY user_status(user_id,status),KEY client_id(client_id),KEY expires(expires))");
$client=yo_client('Legacy Reviewed');$old=['id'=>wp_generate_uuid4(),'client_id'=>$client['client_id'],'user_id'=>$admin->ID,'user_hash'=>hash_hmac('sha256',$admin->ID.'|'.$admin->user_pass.'|'.get_option('fg_oauth_epoch'),wp_salt('auth')),'resource'=>FG_OAuth::resource(),'allow_writes'=>1,'allow_sensitive'=>0,'status'=>'active','created'=>time(),'expires'=>time()+DAY_IN_SECONDS,'last_used'=>0];
$wpdb->insert($gtable,$old);$raw=rtrim(strtr(base64_encode(random_bytes(32)),'+/','-_'),'=');$wpdb->insert(yo_t('tokens'),['hash'=>hash('sha256',$raw),'grant_id'=>$old['id'],'kind'=>'access','status'=>'active','created'=>time(),'expires'=>time()+3600]);
$epoch=get_option('fg_oauth_epoch');$issuer=FG_OAuth::issuer();$resource=FG_OAuth::resource();$oldStored=$wpdb->get_row($wpdb->prepare("SELECT * FROM $gtable WHERE id=%s",$old['id']),ARRAY_A);$oldToken=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.yo_t('tokens').' WHERE hash=%s',hash('sha256',$raw)),ARRAY_A);update_option('fg_oauth_schema','2');
yo_case('real schema v2 upgrade adds default-denied YOLO without changing grants tokens issuer or epoch',function()use($wpdb,$old,$oldStored,$oldToken,$raw,$gtable,$epoch,$issuer,$resource){FG_OAuth::maybe_upgrade();$r=$wpdb->get_row($wpdb->prepare("SELECT * FROM $gtable WHERE id=%s",$old['id']),ARRAY_A);yo_assert(get_option('fg_oauth_schema')==='3'&&(int)$r['allow_yolo']===0,'Migration missing');unset($r['allow_yolo']);yo_assert($r===$oldStored,'Historical grant altered');yo_assert($wpdb->get_row($wpdb->prepare('SELECT * FROM '.yo_t('tokens').' WHERE hash=%s',hash('sha256',$raw)),ARRAY_A)===$oldToken&&get_option('fg_oauth_epoch')===$epoch&&FG_OAuth::issuer()===$issuer&&FG_OAuth::resource()===$resource,'Credential identity changed');});
yo_case('legacy reviewed grant remains reviewed when site enables YOLO',function()use($raw,$old){yo_settings(['write_mode'=>'yolo']);yo_auth($raw);yo_assert(FG_Auth::write_mode()==='reviewed','Old connection elevated');$r=yo_list($old['id']);yo_assert($r['effective_writes']&&!$r['yolo']&&!$r['effective_yolo'],'Legacy UI projection wrong');});
yo_case('pending reviewed consent cannot widen after mode changes to YOLO',function(){yo_settings(['write_mode'=>'reviewed']);yo_login();$c=yo_client();$p=yo_begin($c);yo_assert(!$p['request']['allow_yolo'],'Reviewed request gained YOLO');yo_settings(['write_mode'=>'yolo']);$r=yo_complete($p,$c);yo_auth($r['token']['access_token']);yo_assert((int)$r['grant']['allow_writes']===1&&(int)$r['grant']['allow_yolo']===0&&FG_Auth::write_mode()==='reviewed','Pending consent widened');});
yo_case('pending YOLO consent narrows when site switches to reviewed before approval',function(){yo_settings(['write_mode'=>'yolo']);yo_login();$c=yo_client();$p=yo_begin($c);yo_assert($p['request']['allow_yolo'],'YOLO request missing snapshot');yo_settings(['write_mode'=>'reviewed']);$r=yo_complete($p,$c);yo_settings(['write_mode'=>'yolo']);yo_auth($r['token']['access_token']);yo_assert((int)$r['grant']['allow_yolo']===0&&FG_Auth::write_mode()==='reviewed','Consent revived previously removed YOLO');});
yo_case('pending read-only consent cannot gain writes or YOLO',function(){yo_settings(['writes'=>false,'write_mode'=>'reviewed']);yo_login();$c=yo_client();$p=yo_begin($c);yo_settings(['writes'=>true,'write_mode'=>'yolo']);$r=yo_complete($p,$c);yo_auth($r['token']['access_token']);yo_assert((int)$r['grant']['allow_writes']===0&&(int)$r['grant']['allow_yolo']===0&&FG_Auth::write_mode()==='read_only','Read consent widened');});
yo_case('pending YOLO consent becomes read-only if writes disabled before approval',function(){yo_settings(['write_mode'=>'yolo']);yo_login();$c=yo_client();$p=yo_begin($c);yo_settings(['writes'=>false,'write_mode'=>'yolo']);$r=yo_complete($p,$c);yo_settings(['write_mode'=>'yolo']);yo_auth($r['token']['access_token']);yo_assert((int)$r['grant']['allow_writes']===0&&(int)$r['grant']['allow_yolo']===0&&FG_Auth::write_mode()==='read_only','Disabled writes revived');});
yo_settings(['write_mode'=>'yolo']);$yolo=yo_connect();
yo_case('fresh YOLO approval grants immediate mode and truthful connection projection',function()use($yolo){$i=FG_OAuth::authenticate($yolo['token']['access_token']);yo_auth($yolo['token']['access_token']);$r=yo_list($yolo['grant']['id']);yo_assert($i['writes']&&$i['yolo']&&FG_Auth::write_mode()==='yolo'&&$r['yolo']&&$r['effective_yolo'],'YOLO unavailable after explicit consent');});
yo_case('site changes immediately narrow an authenticated YOLO request even with a stale option cache',function()use($yolo,$wpdb,$base){yo_auth($yolo['token']['access_token']);$cached=FG_Core::settings();$fresh=array_replace($base,['writes'=>false,'write_mode'=>'yolo']);$wpdb->update($wpdb->options,['option_value'=>maybe_serialize($fresh)],['option_name'=>'fg_settings']);yo_assert(FG_Core::settings()===$cached,'Fixture did not preserve stale cache');yo_assert(FG_Auth::write_mode()==='read_only','Cached mode allowed writes');wp_cache_delete('fg_settings','options');wp_cache_delete('alloptions','options');yo_settings(['write_mode'=>'yolo']);});
yo_case('switching YOLO off keeps original consent but requires reviews',function()use($yolo){yo_auth($yolo['token']['access_token']);yo_settings(['write_mode'=>'reviewed']);yo_assert(FG_Auth::write_mode()==='reviewed','YOLO continued after disable');$r=yo_list($yolo['grant']['id']);yo_assert($r['yolo']&&!$r['effective_yolo']&&$r['effective_writes'],'Wrong effective mode');yo_settings(['write_mode'=>'yolo']);});
yo_case('YOLO refresh retains original grant access and identity',function()use(&$yolo){$before=$yolo['grant']['id'];$tokens=yo_refresh($yolo);$yolo['token']=$tokens;$i=FG_OAuth::authenticate($tokens['access_token']);yo_assert(!is_wp_error($i)&&$i['credential_id']===$before&&$i['yolo'],'Refresh lost grant consent');yo_auth($tokens['access_token']);yo_assert(FG_Auth::write_mode()==='yolo','Refresh mode wrong');});
yo_case('reviewed refresh cannot gain YOLO from new site mode',function(){yo_settings(['write_mode'=>'reviewed']);$r=yo_connect();yo_settings(['write_mode'=>'yolo']);$token=yo_refresh($r);$i=FG_OAuth::authenticate($token['access_token']);yo_auth($token['access_token']);yo_assert($i['writes']&&!$i['yolo']&&FG_Auth::write_mode()==='reviewed','Refresh widened old consent');});
yo_case('caller arguments and user agent cannot self-grant YOLO',function(){yo_settings(['write_mode'=>'reviewed']);yo_login();$c=yo_client('YOLO Admin');$_SERVER['HTTP_USER_AGENT']='trusted-yolo-client';$p=yo_begin($c,['allow_yolo'=>'1','write_mode'=>'yolo']);yo_assert(!$p['request']['allow_yolo'],'Untrusted caller set grant mode');$r=yo_complete($p,$c);yo_settings(['write_mode'=>'yolo']);yo_auth($r['token']['access_token']);yo_assert(FG_Auth::write_mode()==='reviewed','Client label widened mode');});
yo_case('YOLO never grants sensitive-data permissions',function()use($yolo){yo_settings(['write_mode'=>'yolo','sensitive'=>true]);yo_auth($yolo['token']['access_token']);yo_assert(FG_Auth::write_mode()==='yolo'&&!FG_Auth::allows_tool(['mutating'=>true,'sensitive'=>true]),'YOLO widened private data access');yo_settings(['write_mode'=>'yolo']);});
yo_case('YOLO preserves native WordPress capability restrictions',function(){global $wpdb;$uid=wp_create_user('yolo-subscriber','fixture-password','subscriber@example.test');$u=get_user_by('id',$uid);$u->set_role('subscriber');yo_settings(['write_mode'=>'yolo','users'=>[$uid]]);yo_login($u);$c=yo_client();$r=yo_complete(yo_begin($c),$c);yo_auth($r['token']['access_token']);yo_assert(FG_Auth::write_mode()==='yolo'&&!FG_Tools::permitted(['mutating'=>true,'sensitive'=>false,'capability'=>'manage_options']),'YOLO elevated WP role');yo_settings(['write_mode'=>'yolo']);});
yo_case('Application Password follows admin mode only within authenticated MCP request',function(){global $admin;yo_settings(['write_mode'=>'yolo']);FG_Auth::reset_context();wp_set_current_user($admin->ID);yo_assert(FG_Auth::write_mode()==='read_only','Cookie-only context gained mode');do_action('application_password_did_authenticate',$admin,['uuid'=>wp_generate_uuid4()]);yo_assert(FG_Auth::write_mode()==='read_only','Pending credential gained mode');$r=new WP_REST_Request('POST','/fames-mcp/v1/mcp');yo_assert(FG_Auth::permission($r)===true&&FG_Auth::write_mode()==='yolo','Application Password mode wrong');yo_settings(['write_mode'=>'reviewed']);yo_assert(FG_Auth::write_mode()==='reviewed','App password ignored narrowed mode');apply_filters('rest_request_after_callbacks',new WP_REST_Response([]),[],$r);yo_assert(FG_Auth::write_mode()==='read_only','Mode survived request reset');yo_settings(['write_mode'=>'yolo']);});
yo_case('removed allowed account immediately loses YOLO and writes',function()use($yolo){yo_auth($yolo['token']['access_token']);yo_settings(['write_mode'=>'yolo','users'=>[]]);yo_assert(FG_Auth::write_mode()==='read_only','Removed user still writes');yo_settings(['write_mode'=>'yolo']);});
yo_case('disabled OAuth immediately removes YOLO write authority',function()use($yolo){yo_auth($yolo['token']['access_token']);yo_settings(['write_mode'=>'yolo','oauth_enabled'=>false]);yo_assert(FG_Auth::write_mode()==='read_only','Disabled OAuth kept write authority');yo_settings(['write_mode'=>'yolo']);});
yo_case('settings storage failure cannot return YOLO mode',function()use($yolo,$wpdb){yo_auth($yolo['token']['access_token']);$fault=static fn($sql)=>str_starts_with($sql,'SELECT option_value FROM ')&&str_contains($sql,"'fg_settings'")?'SELECT * FROM yo_deliberately_missing_settings':$sql;$prior=$wpdb->suppress_errors(true);add_filter('query',$fault);try{yo_assert(FG_Auth::write_mode()==='read_only','Storage failure allowed writes');}finally{remove_filter('query',$fault);$wpdb->suppress_errors($prior);}});
final class YO_DB_Proxy {private $db;public function __construct($db){$this->db=$db;}public function __get($k){return $this->db->$k;}public function __set($k,$v){$this->db->$k=$v;}public function __call($m,$a){$r=$this->db->$m(...$a);return $m==='get_results'&&str_starts_with($a[0]??'','SHOW COLUMNS FROM `'.yo_t('grants').'`')?array_values(array_filter($r,static fn($x)=>$x['Field']!=='allow_yolo')):$r;}}
yo_case('migration marker requires verified allow_yolo column and retry preserves credentials',function()use(&$wpdb,$epoch,$yolo){$real=$wpdb;update_option('fg_oauth_schema','2');$wpdb=new YO_DB_Proxy($real);try{FG_OAuth::install();yo_assert(get_option('fg_oauth_schema')==='2','Marker advanced without column');}finally{$wpdb=$real;}FG_OAuth::maybe_upgrade();yo_assert(get_option('fg_oauth_schema')==='3'&&get_option('fg_oauth_epoch')===$epoch&&!is_wp_error(FG_OAuth::authenticate($yolo['token']['access_token'])),'Retry failed or changed credentials');});
FG_Auth::reset_context();echo json_encode(['passed'=>count(array_filter($results,static fn($r)=>$r['pass'])),'total'=>count($results),'database_class'=>get_class($wpdb),'cases'=>$results],JSON_PRETTY_PRINT);
